# Generated by Django 5.0.2 on 2024-02-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='date_and_time',
            new_name='created_at',
        ),
    ]
