# Generated by Django 5.0.2 on 2024-02-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_rename_sensor_measurement_sensor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor_id',
            new_name='sensor',
        ),
    ]
